#lanuage
language: python
#version
python:
  - "3.6"
# command to install dependencies
install:
  - pip install
  - pip install -r requirements.txt
# command to run tests
script: cd ./api && nosetests

after_success: coveralls